package com.example.taskmanagement.task.repository;

import com.example.taskmanagement.task.entity.Task;
import com.example.taskmanagement.task.entity.TaskStatus;
import com.example.taskmanagement.user.entity.User;
import com.example.taskmanagement.user.repository.UserRepository;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.test.context.DynamicPropertyRegistry;
import org.springframework.test.context.DynamicPropertySource;
import org.testcontainers.containers.PostgreSQLContainer;

import java.util.List;
import java.util.Optional;
import java.util.TimeZone;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.*;

@DataJpaTest
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@DisplayName("TaskRepository Integration Tests")
class TaskRepositoryTest {

    // Manage container instance manually to handle startup fallbacks gracefully
    static PostgreSQLContainer<?> postgres = new PostgreSQLContainer<>("postgres:16-alpine");

    static {
        // Force the JVM default timezone to UTC for the duration of the test.
        // This prevents the PostgreSQL JDBC driver from automatically negotiating the host's "Asia/Saigon" timezone
        // which causes fatal errors on PostgreSQL instances (like Alpine or minimal docker containers) lacking full tzdata.
        TimeZone.setDefault(TimeZone.getTimeZone("UTC"));

        try {
            postgres.start();
            System.out.println(">>> Testcontainers started successfully! Running tests against dynamic PostgreSQL container. <<<");
        } catch (Exception e) {
            System.err.println(">>> Testcontainers failed to start: " + e.getMessage() + ". <<<");
            System.err.println(">>> Hybrid Fallback: Redirecting integration tests to the local running PostgreSQL instance at localhost:5432. <<<");
        }
    }

    @DynamicPropertySource
    static void configureProperties(DynamicPropertyRegistry registry) {
        if (postgres.isRunning()) {
            registry.add("spring.datasource.url", () -> postgres.getJdbcUrl() + "&options=-c%20timezone=UTC");
            registry.add("spring.datasource.username", postgres::getUsername);
            registry.add("spring.datasource.password", postgres::getPassword);
            registry.add("spring.jpa.hibernate.ddl-auto", () -> "create-drop");
        } else {
            // Fallback to the active database on host running on Docker
            registry.add("spring.datasource.url", () -> "jdbc:postgresql://localhost:5432/tasks2db?options=-c%20timezone=UTC");
            registry.add("spring.datasource.username", () -> "postgres");
            registry.add("spring.datasource.password", () -> "postgres");
            registry.add("spring.jpa.hibernate.ddl-auto", () -> "update");
        }
        registry.add("spring.jpa.show-sql", () -> "true");
    }

    @Autowired
    private TaskRepository taskRepository;

    @Autowired
    private UserRepository userRepository;

    private User savedUser;

    @BeforeEach
    void setUp() {
        // Clear repositories prior to each test to ensure complete isolation
        taskRepository.deleteAll();
        userRepository.deleteAll();

        // Create and persist owner User
        User user = User.builder()
                .id(UUID.randomUUID()) // User ID is manually supplied in this system
                .username("john_doe")
                .email("john.doe@example.com")
                .build();
        savedUser = userRepository.saveAndFlush(user);
    }

    @Test
    @DisplayName("Should successfully persist a new task and populate auto-generated fields")
    void save_Success() {
        // Arrange
        Task task = Task.builder()
                .title("Complete repository test")
                .description("Write and run integration tests using PostgreSQL")
                .status(TaskStatus.PENDING)
                .user(savedUser)
                .build();

        // Act
        Task savedTask = taskRepository.saveAndFlush(task);

        // Assert
        assertNotNull(savedTask.getId(), "Task ID should be auto-generated by the DB");
        assertEquals(task.getTitle(), savedTask.getTitle());
        assertEquals(task.getDescription(), savedTask.getDescription());
        assertEquals(TaskStatus.PENDING, savedTask.getStatus());
        assertEquals(savedUser.getId(), savedTask.getUser().getId());
        assertNotNull(savedTask.getCreatedAt(), "CreatedAt timestamp should be auto-populated");
        assertNotNull(savedTask.getUpdatedAt(), "UpdatedAt timestamp should be auto-populated");
    }

    @Test
    @DisplayName("Should successfully find an existing task by its ID")
    void findById_Success() {
        // Arrange
        Task task = Task.builder()
                .title("Read database logs")
                .description("Analyze generated sql queries")
                .status(TaskStatus.IN_PROGRESS)
                .user(savedUser)
                .build();
        Task savedTask = taskRepository.saveAndFlush(task);

        // Act
        Optional<Task> foundTaskOpt = taskRepository.findById(savedTask.getId());

        // Assert
        assertTrue(foundTaskOpt.isPresent(), "Task must be present in database");
        Task foundTask = foundTaskOpt.get();
        assertEquals(savedTask.getId(), foundTask.getId());
        assertEquals("Read database logs", foundTask.getTitle());
        assertEquals(TaskStatus.IN_PROGRESS, foundTask.getStatus());
    }

    @Test
    @DisplayName("Should return empty optional when finding a non-existent task ID")
    void findById_NotFound() {
        // Act
        Optional<Task> foundTaskOpt = taskRepository.findById(UUID.randomUUID());

        // Assert
        assertTrue(foundTaskOpt.isEmpty(), "Optional should be empty for non-existent ID");
    }

    @Test
    @DisplayName("Should retrieve all tasks belonging to a specific user ID")
    void findAllByUserId_Success() {
        // Arrange
        Task task1 = Task.builder()
                .title("Task 1")
                .description("First description")
                .status(TaskStatus.PENDING)
                .user(savedUser)
                .build();

        Task task2 = Task.builder()
                .title("Task 2")
                .description("Second description")
                .status(TaskStatus.COMPLETED)
                .user(savedUser)
                .build();

        // Save a task belonging to a different user to verify filtering isolation
        User otherUser = User.builder()
                .id(UUID.randomUUID())
                .username("other_user")
                .email("other@example.com")
                .build();
        User savedOtherUser = userRepository.saveAndFlush(otherUser);

        Task otherTask = Task.builder()
                .title("Other task")
                .description("Should not be returned")
                .status(TaskStatus.PENDING)
                .user(savedOtherUser)
                .build();

        taskRepository.saveAllAndFlush(List.of(task1, task2, otherTask));

        // Act
        List<Task> userTasks = taskRepository.findAllByUserId(savedUser.getId());

        // Assert
        assertNotNull(userTasks);
        assertEquals(2, userTasks.size(), "Should only return the 2 tasks belonging to savedUser");
        assertTrue(userTasks.stream().anyMatch(t -> t.getTitle().equals("Task 1")));
        assertTrue(userTasks.stream().anyMatch(t -> t.getTitle().equals("Task 2")));
        assertTrue(userTasks.stream().noneMatch(t -> t.getTitle().equals("Other task")), "Should not leak other user's tasks");
    }

    @Test
    @DisplayName("Should successfully delete a task by its ID")
    void deleteById_Success() {
        // Arrange
        Task task = Task.builder()
                .title("Task to Delete")
                .description("This will be removed")
                .status(TaskStatus.PENDING)
                .user(savedUser)
                .build();
        Task savedTask = taskRepository.saveAndFlush(task);
        assertTrue(taskRepository.existsById(savedTask.getId()), "Task must exist before deletion");

        // Act
        taskRepository.deleteById(savedTask.getId());
        taskRepository.flush();

        // Assert
        assertFalse(taskRepository.existsById(savedTask.getId()), "Task must no longer exist after deletion");
    }

    @Test
    @DisplayName("Should return correct existence flag when existsById is invoked")
    void existsById_Success() {
        // Arrange
        Task task = Task.builder()
                .title("Task to check existence")
                .description("Checking exist flag")
                .status(TaskStatus.COMPLETED)
                .user(savedUser)
                .build();
        Task savedTask = taskRepository.saveAndFlush(task);

        // Act & Assert
        assertTrue(taskRepository.existsById(savedTask.getId()), "existsById must return true for saved task");
        assertFalse(taskRepository.existsById(UUID.randomUUID()), "existsById must return false for random UUID");
    }
}
